function generateWords(amount) {
  const indexes = [];
  while (indexes.length < amount) {
    const n = Math.floor(Math.random() * words.length) + 1;
    if (indexes.indexOf(n === -1)) {
      indexes.push(n);
    }
  }
  return indexes.map(i => words[i]);
}


const words = [
  'insect',
  'queen',
  'piano',
  'classroom',
  'airport',
  'apartment',
  'medicine',
  'space',
  'movie',
  'Donald Trump',
  'juggle',
  'sniper',
  'death',
  'fishing',
  'war',
  'punching',
  'boxing match',
  'philosophy',
  'lecture',
  'George Washington',
  'exam',
  'van',
  'army',
  'Chinese',
  'leader',
  'president',
  'language',
  'race car',
  'pole jump',
  'sky diving',
  'funeral',
  'wedding',
  'art',
  'magazine',
  'black hole',
  'highway',
  'professor',
  'virus',
  'stranger',
  'winner',
  'director',
  'billionaire',
  'surgery',
  'chemistry',
  'king',
  'sword fight',
  'internet',
  'dad',
  'construction',
  'traffic',
  'fortune',
  'groceries',
  'police',
  'bank robber',
  'snowstorm',
  'proposal',
  'poem',
  'Confucius',
  'injury',
  'singer',
  'jungle',
  'belly flop',
  't-bone steak',
  'multiple choice',
  'rock band',
  'poor',
  'acorn',
  'smoothie',
  'macbook',
  'toilet',
  'headphones',
  'beer',
  'steering wheel',
  'pregnant',
  'video game',
  'work from home',
  'maternity leave',
  'elastic',
  'high school',
  'e-mail',
  'oil',
  'coronavirus',
  'greasy hair',
  'nail clippers',
  'violin',
  'mousepad',
  'god',
  'gangster',
  'princess',
  'mason jar',
  'zombie',
  'electricity',
  'drawer',
  'orange juice',
  'Autumn',
  'Halloween',
  'first class',
  'bass',
  'text message',
  'dirty',
  'Obama',
  'Fortnite',
  'mirror',
  'alarm',
  'thunder',
  'Three Little Pigs',
  'toilet paper',
  'mushrooms',
  'eye shadow',
  'pumpkin pie',
  'junk mail',
  'birthday',
  'full moon',
  'WiFi',
  'hotel',
  'seat belt',
  'dizzy',
  'deodorant',
  'vegetarian',
  'ring leader',
  'magnet',
  'chain saw',
  'ferris wheel',
  'pigtails',
  'unicorn',
  'black and white',
  'cord',
  'snail',
  'kangaroo',
  'face mask',
  'quarantine',
  'bat',
  'brain',
  'rat',
  'batman',
  'mowing the lawn',
  'dirt cheap',
  'McDonald\'s',
  'big nose',
  'teeth gap',
  'lottery',
];

module.exports = {
  generateWords,
};
